### ISSUE TITLE
remove users from temporary groups - Cronjob

### ISSUE THREAD

**Issue by ghost** [wbbaddons/de.joshsboard.tempusergroup#2]
unable to find class 'wcf\system\cronjob\RemoveUserFromGroupCronjob'
0
/var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/system/cronjob/CronjobScheduler.class.php
161
#0 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/system/cronjob/CronjobScheduler.class.php(71): wcf\system\cronjob\CronjobScheduler->executeCronjob(Object(wcf\data\cronjob\CronjobEditor), Object(wcf\data\cronjob\log\CronjobLogEditor))
#1 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/data/cronjob/CronjobAction.class.php(213): wcf\system\cronjob\CronjobScheduler->executeCronjobs()
#2 [internal function]: wcf\data\cronjob\CronjobAction->executeCronjobs()
#3 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/data/AbstractDatabaseObjectAction.class.php(171): call_user_func(Array)
#4 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/action/AJAXProxyAction.class.php(76): wcf\data\AbstractDatabaseObjectAction->executeAction()
#5 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/action/AJAXInvokeAction.class.php(96): wcf\action\AJAXProxyAction->invoke()
#6 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/action/AbstractAction.class.php(49): wcf\action\AJAXInvokeAction->execute()
#7 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/action/AJAXInvokeAction.class.php(63): wcf\action\AbstractAction->__run()
#8 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/system/request/Request.class.php(58): wcf\action\AJAXInvokeAction->__run()
#9 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/wcf/lib/system/request/RequestHandler.class.php(94): wcf\system\request\Request->execute()
#10 /var/www/vhosts/wbb-center.net/httpdocs/wbb4/index.php(10): wcf\system\request\RequestHandler->handle('wbb')
#11 {main}

**Comment by Fighter456** [comment]
@Stubs Please avoid in the future, that you reference other issues by using the "GitHub Flavored Markdown".
Error messages can also be read better, as the formatting is retained.
